build_root:
  project_image:
    dockerfile_literal: "FROM registry.access.redhat.com/ubi9:latest\nUSER 0\nRUN
      dnf -y install \\\n  git \\\n  make \\\n  python3 \\\n  python3-pip \n"
  use_build_cache: true
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: make-all
  commands: |
    make all
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: openshift-kni
  repo: telco5g-konflux
