build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.21
releases:
  latest:
    release:
      product: ocp
      channel: candidate
      version: "4.16"
resources:
  '*':
    limits:
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
tests:
- as: kpi-results-416-candidate
  cluster: build05
  # The upstream KPI job runs on an internal jenkins
  # For 4.16, it is currently disabled. Will be re-enabled soon and cron updated
  cron: "@yearly"
  steps:
    env:
      KPI_DESCRIPTION: "RAN RDS SPR-EE"
    workflow: telco5g-kpi-results
# The branches below don't exist but the ci-tooling requires them to be unique
# This is fine because we aren't checking out any repo for this job anyway
zz_generated_metadata:
  branch: master-416
  org: ran-telco5g
  repo: kpi-results
